package culture

import "github.com/thalesfu/ck2nebula"

var (
	Culture_阿尔泰_女真 = &ck2nebula.Culture{
		VID:                   "culture.jurchen",
		Name:                  "女真",
		Code:                  "jurchen",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      true,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          true,
	}
	Culture_阿尔泰_葛逻禄 = &ck2nebula.Culture{
		VID:                   "culture.karluk",
		Name:                  "葛逻禄",
		Code:                  "karluk",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     true,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          true,
	}
	Culture_阿尔泰_契丹 = &ck2nebula.Culture{
		VID:                   "culture.khitan",
		Name:                  "契丹",
		Code:                  "khitan",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     true,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      true,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          true,
	}
	Culture_阿尔泰_黠戛斯 = &ck2nebula.Culture{
		VID:                   "culture.kirghiz",
		Name:                  "黠戛斯",
		Code:                  "kirghiz",
		FromDynastyPrefix:     "of ",
		MaleParonym:           " uulu",
		FemaleParonym:         " kyzy",
		DynastyTitleNames:     false,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          true,
	}
	Culture_阿尔泰_蒙古 = &ck2nebula.Culture{
		VID:                   "culture.mongol",
		Name:                  "蒙古",
		Code:                  "mongol",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          true,
	}
	Culture_阿尔泰_回鹘 = &ck2nebula.Culture{
		VID:                   "culture.uyghur",
		Name:                  "回鹘",
		Code:                  "uyghur",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          true,
	}
	Culture_阿拉伯_安达卢西亚 = &ck2nebula.Culture{
		VID:                   "culture.andalusian_arabic",
		Name:                  "安达卢西亚",
		Code:                  "andalusian_arabic",
		FromDynastyPrefix:     "mn ",
		MaleParonym:           "ibn ",
		FemaleParonym:         "bint ",
		DynastyTitleNames:     true,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_阿拉伯_埃及 = &ck2nebula.Culture{
		VID:                   "culture.egyptian_arabic",
		Name:                  "埃及",
		Code:                  "egyptian_arabic",
		FromDynastyPrefix:     "mn ",
		MaleParonym:           "ibn ",
		FemaleParonym:         "bint ",
		DynastyTitleNames:     true,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_阿拉伯_黎凡特 = &ck2nebula.Culture{
		VID:                   "culture.levantine_arabic",
		Name:                  "黎凡特",
		Code:                  "levantine_arabic",
		FromDynastyPrefix:     "mn ",
		MaleParonym:           "ibn ",
		FemaleParonym:         "bint ",
		DynastyTitleNames:     true,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_波罗的_拉特加莱 = &ck2nebula.Culture{
		VID:                   "culture.lettigallish",
		Name:                  "拉特加莱",
		Code:                  "lettigallish",
		FromDynastyPrefix:     "gada ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_波罗的_立陶宛 = &ck2nebula.Culture{
		VID:                   "culture.lithuanian",
		Name:                  "立陶宛",
		Code:                  "lithuanian",
		FromDynastyPrefix:     "iš ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_波罗的_普鲁士 = &ck2nebula.Culture{
		VID:                   "culture.prussian",
		Name:                  "普鲁士",
		Code:                  "prussian",
		FromDynastyPrefix:     "iš ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_熊_熊 = &ck2nebula.Culture{
		VID:                   "culture.bear",
		Name:                  "熊",
		Code:                  "bear",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_拜占庭_阿兰 = &ck2nebula.Culture{
		VID:                   "culture.alan",
		Name:                  "阿兰",
		Code:                  "alan",
		FromDynastyPrefix:     "ve ",
		MaleParonym:           "y fyrt",
		FemaleParonym:         "y chyzg",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_拜占庭_阿尔贝里亚 = &ck2nebula.Culture{
		VID:                   "culture.arberian",
		Name:                  "阿尔贝里亚",
		Code:                  "arberian",
		FromDynastyPrefix:     "e ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_拜占庭_亚美尼亚 = &ck2nebula.Culture{
		VID:                   "culture.armenian",
		Name:                  "亚美尼亚",
		Code:                  "armenian",
		FromDynastyPrefix:     "ve ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_拜占庭_亚述 = &ck2nebula.Culture{
		VID:                   "culture.assyrian",
		Name:                  "亚述",
		Code:                  "assyrian",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "Bar ",
		FemaleParonym:         "Barta ",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_拜占庭_哥特 = &ck2nebula.Culture{
		VID:                   "culture.crimean_gothic",
		Name:                  "哥特",
		Code:                  "crimean_gothic",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_拜占庭_格鲁吉亚 = &ck2nebula.Culture{
		VID:                   "culture.georgian",
		Name:                  "格鲁吉亚",
		Code:                  "georgian",
		FromDynastyPrefix:     "ve ",
		MaleParonym:           "s dze",
		FemaleParonym:         "shvili",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_拜占庭_希腊 = &ck2nebula.Culture{
		VID:                   "culture.greek",
		Name:                  "希腊",
		Code:                  "greek",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_猫_猫 = &ck2nebula.Culture{
		VID:                   "culture.cat",
		Name:                  "猫",
		Code:                  "cat",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_凯尔特_布列塔尼 = &ck2nebula.Culture{
		VID:                   "culture.breton",
		Name:                  "布列塔尼",
		Code:                  "breton",
		FromDynastyPrefix:     "de ",
		MaleParonym:           "mab ",
		FemaleParonym:         "verch ",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      true,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_凯尔特_爱尔兰 = &ck2nebula.Culture{
		VID:                   "culture.irish",
		Name:                  "爱尔兰",
		Code:                  "irish",
		FromDynastyPrefix:     "de ",
		MaleParonym:           "mac ",
		FemaleParonym:         "nic ",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      true,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_凯尔特_皮克特 = &ck2nebula.Culture{
		VID:                   "culture.pictish",
		Name:                  "皮克特",
		Code:                  "pictish",
		FromDynastyPrefix:     "",
		MaleParonym:           "map ",
		FemaleParonym:         "verch ",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      true,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_凯尔特_苏格兰 = &ck2nebula.Culture{
		VID:                   "culture.scottish",
		Name:                  "苏格兰",
		Code:                  "scottish",
		FromDynastyPrefix:     "de ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      true,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_凯尔特_威尔士 = &ck2nebula.Culture{
		VID:                   "culture.welsh",
		Name:                  "威尔士",
		Code:                  "welsh",
		FromDynastyPrefix:     "de ",
		MaleParonym:           "ap ",
		FemaleParonym:         "ferch ",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      true,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_中非_豪萨 = &ck2nebula.Culture{
		VID:                   "culture.hausa",
		Name:                  "豪萨",
		Code:                  "hausa",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_中非_卡努里 = &ck2nebula.Culture{
		VID:                   "culture.kanuri",
		Name:                  "卡努里",
		Code:                  "kanuri",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_中非_扎加瓦 = &ck2nebula.Culture{
		VID:                   "culture.zaghawa",
		Name:                  "扎加瓦",
		Code:                  "zaghawa",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_中日耳曼_日耳曼 = &ck2nebula.Culture{
		VID:                   "culture.german",
		Name:                  "日耳曼",
		Code:                  "german",
		FromDynastyPrefix:     "von ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_中日耳曼_伦巴第 = &ck2nebula.Culture{
		VID:                   "culture.lombard",
		Name:                  "伦巴第",
		Code:                  "lombard",
		FromDynastyPrefix:     "de ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_中日耳曼_法兰克 = &ck2nebula.Culture{
		VID:                   "culture.old_frankish",
		Name:                  "法兰克",
		Code:                  "old_frankish",
		FromDynastyPrefix:     "de ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_中日耳曼_苏维汇 = &ck2nebula.Culture{
		VID:                   "culture.suebi",
		Name:                  "苏维汇",
		Code:                  "suebi",
		FromDynastyPrefix:     "von ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_中华_汉 = &ck2nebula.Culture{
		VID:                   "culture.han",
		Name:                  "汉",
		Code:                  "han",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      true,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_犬科_狗 = &ck2nebula.Culture{
		VID:                   "culture.dog_culture",
		Name:                  "狗",
		Code:                  "dog_culture",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_龙科_龙 = &ck2nebula.Culture{
		VID:                   "culture.dragon_culture",
		Name:                  "龙",
		Code:                  "dragon_culture",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          true,
	}
	Culture_鸟类_鸭 = &ck2nebula.Culture{
		VID:                   "culture.duck_culture",
		Name:                  "鸭",
		Code:                  "duck_culture",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          true,
	}
	Culture_东非_达朱 = &ck2nebula.Culture{
		VID:                   "culture.daju",
		Name:                  "达朱",
		Code:                  "daju",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      true,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          true,
	}
	Culture_东非_埃塞俄比亚 = &ck2nebula.Culture{
		VID:                   "culture.ethiopian",
		Name:                  "埃塞俄比亚",
		Code:                  "ethiopian",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      true,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_东非_努比亚 = &ck2nebula.Culture{
		VID:                   "culture.nubian",
		Name:                  "努比亚",
		Code:                  "nubian",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      true,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_东非_索马里 = &ck2nebula.Culture{
		VID:                   "culture.somali",
		Name:                  "索马里",
		Code:                  "somali",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      true,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_东斯拉夫_伊尔门 = &ck2nebula.Culture{
		VID:                   "culture.ilmenian",
		Name:                  "伊尔门",
		Code:                  "ilmenian",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "ovich",
		FemaleParonym:         "ovna",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_东斯拉夫_罗斯 = &ck2nebula.Culture{
		VID:                   "culture.russian",
		Name:                  "罗斯",
		Code:                  "russian",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "ovich",
		FemaleParonym:         "ovna",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_东斯拉夫_西维利亚 = &ck2nebula.Culture{
		VID:                   "culture.severian",
		Name:                  "西维利亚",
		Code:                  "severian",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "ovich",
		FemaleParonym:         "ovna",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_东斯拉夫_沃里尼亚 = &ck2nebula.Culture{
		VID:                   "culture.volhynian",
		Name:                  "沃里尼亚",
		Code:                  "volhynian",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "ovich",
		FemaleParonym:         "ovna",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_长鼻目_象 = &ck2nebula.Culture{
		VID:                   "culture.elephant_culture",
		Name:                  "象",
		Code:                  "elephant_culture",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_芬兰_乌戈尔_芬兰 = &ck2nebula.Culture{
		VID:                   "culture.finnish",
		Name:                  "芬兰",
		Code:                  "finnish",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_芬兰_乌戈尔_汉特 = &ck2nebula.Culture{
		VID:                   "culture.khanty",
		Name:                  "汉特",
		Code:                  "khanty",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_芬兰_乌戈尔_科米 = &ck2nebula.Culture{
		VID:                   "culture.komi",
		Name:                  "科米",
		Code:                  "komi",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_芬兰_乌戈尔_萨米 = &ck2nebula.Culture{
		VID:                   "culture.lappish",
		Name:                  "萨米",
		Code:                  "lappish",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_芬兰_乌戈尔_梅晓拉 = &ck2nebula.Culture{
		VID:                   "culture.meshchera",
		Name:                  "梅晓拉",
		Code:                  "meshchera",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_芬兰_乌戈尔_莫尔多瓦 = &ck2nebula.Culture{
		VID:                   "culture.mordvin",
		Name:                  "莫尔多瓦",
		Code:                  "mordvin",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_芬兰_乌戈尔_爱沙尼亚 = &ck2nebula.Culture{
		VID:                   "culture.ugricbaltic",
		Name:                  "爱沙尼亚",
		Code:                  "ugricbaltic",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_猬科_刺猬 = &ck2nebula.Culture{
		VID:                   "culture.hedgehog_culture",
		Name:                  "刺猬",
		Code:                  "hedgehog_culture",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          true,
	}
	Culture_马_马 = &ck2nebula.Culture{
		VID:                   "culture.horse",
		Name:                  "马",
		Code:                  "horse",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_伊比利亚_巴斯克 = &ck2nebula.Culture{
		VID:                   "culture.basque",
		Name:                  "巴斯克",
		Code:                  "basque",
		FromDynastyPrefix:     "de ",
		MaleParonym:           "ez",
		FemaleParonym:         "ez",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_伊比利亚_卡斯蒂利亚 = &ck2nebula.Culture{
		VID:                   "culture.castillan",
		Name:                  "卡斯蒂利亚",
		Code:                  "castillan",
		FromDynastyPrefix:     "de ",
		MaleParonym:           "ez",
		FemaleParonym:         "ez",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_伊比利亚_加泰罗尼亚 = &ck2nebula.Culture{
		VID:                   "culture.catalan",
		Name:                  "加泰罗尼亚",
		Code:                  "catalan",
		FromDynastyPrefix:     "de ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_伊比利亚_葡萄牙 = &ck2nebula.Culture{
		VID:                   "culture.portuguese",
		Name:                  "葡萄牙",
		Code:                  "portuguese",
		FromDynastyPrefix:     "de ",
		MaleParonym:           "es",
		FemaleParonym:         "es",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_伊比利亚_西哥特 = &ck2nebula.Culture{
		VID:                   "culture.visigothic",
		Name:                  "西哥特",
		Code:                  "visigothic",
		FromDynastyPrefix:     "de ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_印度雅利安_尼波罗 = &ck2nebula.Culture{
		VID:                   "culture.nepali",
		Name:                  "尼波罗",
		Code:                  "nepali",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      true,
		CountTitlesHidden:     true,
		BaronTitlesHidden:     true,
		AllowLooting:          true,
	}
	Culture_伊朗_阿富汗 = &ck2nebula.Culture{
		VID:                   "culture.afghan",
		Name:                  "阿富汗",
		Code:                  "afghan",
		FromDynastyPrefix:     "",
		MaleParonym:           "zai",
		FemaleParonym:         "lur",
		DynastyTitleNames:     true,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_伊朗_库尔德 = &ck2nebula.Culture{
		VID:                   "culture.kurdish",
		Name:                  "库尔德",
		Code:                  "kurdish",
		FromDynastyPrefix:     "",
		MaleParonym:           "kurê ",
		FemaleParonym:         "kiçê ",
		DynastyTitleNames:     true,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_伊朗_波斯 = &ck2nebula.Culture{
		VID:                   "culture.persian",
		Name:                  "波斯",
		Code:                  "persian",
		FromDynastyPrefix:     "",
		MaleParonym:           "zade",
		FemaleParonym:         "dokht",
		DynastyTitleNames:     true,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_伊朗_塞种 = &ck2nebula.Culture{
		VID:                   "culture.saka",
		Name:                  "塞种",
		Code:                  "saka",
		FromDynastyPrefix:     "nava ",
		MaleParonym:           "puri ",
		FemaleParonym:         "duda ",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      true,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_伊朗_粟特 = &ck2nebula.Culture{
		VID:                   "culture.sogdian",
		Name:                  "粟特",
		Code:                  "sogdian",
		FromDynastyPrefix:     "m ",
		MaleParonym:           "zk ",
		FemaleParonym:         "zk ",
		DynastyTitleNames:     false,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      true,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_伊朗_吐火罗 = &ck2nebula.Culture{
		VID:                   "culture.tocharian",
		Name:                  "吐火罗",
		Code:                  "tocharian",
		FromDynastyPrefix:     "mem ",
		MaleParonym:           "soyä ",
		FemaleParonym:         "tkacer ",
		DynastyTitleNames:     false,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      true,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_以色列_阿什肯纳兹 = &ck2nebula.Culture{
		VID:                   "culture.ashkenazi",
		Name:                  "阿什肯纳兹",
		Code:                  "ashkenazi",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_以色列_塞法迪 = &ck2nebula.Culture{
		VID:                   "culture.sephardi",
		Name:                  "塞法迪",
		Code:                  "sephardi",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_拉丁_达尔马提亚 = &ck2nebula.Culture{
		VID:                   "culture.dalmatian",
		Name:                  "达尔马提亚",
		Code:                  "dalmatian",
		FromDynastyPrefix:     "di ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_拉丁_法兰西 = &ck2nebula.Culture{
		VID:                   "culture.frankish",
		Name:                  "法兰西",
		Code:                  "frankish",
		FromDynastyPrefix:     "de ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_拉丁_意大利 = &ck2nebula.Culture{
		VID:                   "culture.italian",
		Name:                  "意大利",
		Code:                  "italian",
		FromDynastyPrefix:     "di ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_拉丁_诺曼 = &ck2nebula.Culture{
		VID:                   "culture.norman",
		Name:                  "诺曼",
		Code:                  "norman",
		FromDynastyPrefix:     "de ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_拉丁_奥克 = &ck2nebula.Culture{
		VID:                   "culture.occitan",
		Name:                  "奥克",
		Code:                  "occitan",
		FromDynastyPrefix:     "de ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_拉丁_罗马 = &ck2nebula.Culture{
		VID:                   "culture.roman",
		Name:                  "罗马",
		Code:                  "roman",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_拉丁_撒丁 = &ck2nebula.Culture{
		VID:                   "culture.sardinian",
		Name:                  "撒丁",
		Code:                  "sardinian",
		FromDynastyPrefix:     "de ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_马扎尔_匈牙利 = &ck2nebula.Culture{
		VID:                   "culture.hungarian",
		Name:                  "匈牙利",
		Code:                  "hungarian",
		FromDynastyPrefix:     "a ",
		MaleParonym:           "fi",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      true,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          true,
	}
	Culture_中美洲_纳瓦 = &ck2nebula.Culture{
		VID:                   "culture.nahuatl",
		Name:                  "纳瓦",
		Code:                  "nahuatl",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          true,
	}
	Culture_北日耳曼_丹麦 = &ck2nebula.Culture{
		VID:                   "culture.danish",
		Name:                  "丹麦",
		Code:                  "danish",
		FromDynastyPrefix:     "af ",
		MaleParonym:           "sen",
		FemaleParonym:         "sdatter",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      true,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_北日耳曼_诺斯 = &ck2nebula.Culture{
		VID:                   "culture.norse",
		Name:                  "诺斯",
		Code:                  "norse",
		FromDynastyPrefix:     "af ",
		MaleParonym:           "sson",
		FemaleParonym:         "sdottir",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      true,
		CountTitlesHidden:     true,
		BaronTitlesHidden:     true,
		AllowLooting:          true,
	}
	Culture_北日耳曼_挪威 = &ck2nebula.Culture{
		VID:                   "culture.norwegian",
		Name:                  "挪威",
		Code:                  "norwegian",
		FromDynastyPrefix:     "av ",
		MaleParonym:           "sson",
		FemaleParonym:         "sdatter",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      true,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_北日耳曼_瑞典 = &ck2nebula.Culture{
		VID:                   "culture.swedish",
		Name:                  "瑞典",
		Code:                  "swedish",
		FromDynastyPrefix:     "af ",
		MaleParonym:           "sson",
		FemaleParonym:         "sdotter",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      true,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_熊猫科_小熊猫 = &ck2nebula.Culture{
		VID:                   "culture.red_panda",
		Name:                  "小熊猫",
		Code:                  "red_panda",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_南斯拉夫_波斯尼亚 = &ck2nebula.Culture{
		VID:                   "culture.bosnian",
		Name:                  "波斯尼亚",
		Code:                  "bosnian",
		FromDynastyPrefix:     "od ",
		MaleParonym:           "ic",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_南斯拉夫_保加利亚 = &ck2nebula.Culture{
		VID:                   "culture.bulgarian",
		Name:                  "保加利亚",
		Code:                  "bulgarian",
		FromDynastyPrefix:     "ot ",
		MaleParonym:           "ov",
		FemaleParonym:         "ova",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_南斯拉夫_卡拉塔尼亚 = &ck2nebula.Culture{
		VID:                   "culture.carantanian",
		Name:                  "卡拉塔尼亚",
		Code:                  "carantanian",
		FromDynastyPrefix:     "od ",
		MaleParonym:           "ic",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_南斯拉夫_克罗地亚 = &ck2nebula.Culture{
		VID:                   "culture.croatian",
		Name:                  "克罗地亚",
		Code:                  "croatian",
		FromDynastyPrefix:     "od ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_南斯拉夫_瓦拉几亚 = &ck2nebula.Culture{
		VID:                   "culture.romanian",
		Name:                  "瓦拉几亚",
		Code:                  "romanian",
		FromDynastyPrefix:     "de ",
		MaleParonym:           "escu",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_南斯拉夫_塞尔维亚 = &ck2nebula.Culture{
		VID:                   "culture.serbian",
		Name:                  "塞尔维亚",
		Code:                  "serbian",
		FromDynastyPrefix:     "od ",
		MaleParonym:           "ic",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_藏缅_党项 = &ck2nebula.Culture{
		VID:                   "culture.tangut",
		Name:                  "党项",
		Code:                  "tangut",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      true,
		DukesCalledKings:      true,
		CountTitlesHidden:     true,
		BaronTitlesHidden:     true,
		AllowLooting:          true,
	}
	Culture_藏缅_象雄 = &ck2nebula.Culture{
		VID:                   "culture.zhangzhung",
		Name:                  "象雄",
		Code:                  "zhangzhung",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      true,
		DukesCalledKings:      true,
		CountTitlesHidden:     true,
		BaronTitlesHidden:     true,
		AllowLooting:          true,
	}
	Culture_西非_曼德 = &ck2nebula.Culture{
		VID:                   "culture.manden",
		Name:                  "曼德",
		Code:                  "manden",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: true,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_西非_桑海 = &ck2nebula.Culture{
		VID:                   "culture.songhay",
		Name:                  "桑海",
		Code:                  "songhay",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_西非_索宁凯 = &ck2nebula.Culture{
		VID:                   "culture.soninke",
		Name:                  "索宁凯",
		Code:                  "soninke",
		FromDynastyPrefix:     "",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_西日耳曼_荷兰 = &ck2nebula.Culture{
		VID:                   "culture.dutch",
		Name:                  "荷兰",
		Code:                  "dutch",
		FromDynastyPrefix:     "van ",
		MaleParonym:           "szoon",
		FemaleParonym:         "sdochter",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_西日耳曼_英格兰 = &ck2nebula.Culture{
		VID:                   "culture.english",
		Name:                  "英格兰",
		Code:                  "english",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_西日耳曼_弗里斯兰 = &ck2nebula.Culture{
		VID:                   "culture.frisian",
		Name:                  "弗里斯兰",
		Code:                  "frisian",
		FromDynastyPrefix:     "von ",
		MaleParonym:           "sson",
		FemaleParonym:         "sdohtor",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     true,
		BaronTitlesHidden:     true,
		AllowLooting:          false,
	}
	Culture_西日耳曼_撒克逊 = &ck2nebula.Culture{
		VID:                   "culture.old_saxon",
		Name:                  "撒克逊",
		Code:                  "old_saxon",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "sson",
		FemaleParonym:         "sdohtor",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     true,
		BaronTitlesHidden:     true,
		AllowLooting:          false,
	}
	Culture_西日耳曼_盎格鲁_撒克逊 = &ck2nebula.Culture{
		VID:                   "culture.saxon",
		Name:                  "盎格鲁－撒克逊",
		Code:                  "saxon",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "sson",
		FemaleParonym:         "sdohtor",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      true,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_西斯拉夫_波希米亚 = &ck2nebula.Culture{
		VID:                   "culture.bohemian",
		Name:                  "波希米亚",
		Code:                  "bohemian",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_西斯拉夫_波兰 = &ck2nebula.Culture{
		VID:                   "culture.polish",
		Name:                  "波兰",
		Code:                  "polish",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_西斯拉夫_波美拉尼亚 = &ck2nebula.Culture{
		VID:                   "culture.pommeranian",
		Name:                  "波美拉尼亚",
		Code:                  "pommeranian",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
	Culture_西斯拉夫_斯洛伐克 = &ck2nebula.Culture{
		VID:                   "culture.slovieni",
		Name:                  "斯洛伐克",
		Code:                  "slovieni",
		FromDynastyPrefix:     "of ",
		MaleParonym:           "",
		FemaleParonym:         "",
		DynastyTitleNames:     false,
		FounderNamedDynasties: false,
		Caste:                 false,
		DynastyNameFirst:      false,
		DukesCalledKings:      false,
		CountTitlesHidden:     false,
		BaronTitlesHidden:     false,
		AllowLooting:          false,
	}
)
